// Le dictionnaire des noms de pages publiées (17/09/2026).
//
// Une page publiée sur le web porte un nom de **trois mots** plutôt qu'une
// suite de caractères aléatoires : `galeries-joyeux-falaise` se dicte au
// téléphone, se recopie depuis une diapositive, se reconnaît dans une
// liste. Une adresse publique sert précisément à circuler hors de l'écran.
//
// **D'où vient cette liste.** C'est la liste française de BIP-39, faite
// pour être lue, dictée et retapée sans ambiguïté : pas d'homophones qui
// se confondent, et les quatre premières lettres de chaque mot sont
// uniques, si bien qu'une faute de frappe en fin de mot reste
// rattrapable. Domaine public (dépôt bitcoin/bips).
//
// **Ce qu'on en a retiré** : les 366 mots portant un accent ou un
// caractère non ASCII — une adresse ne doit pas dépendre de la façon dont
// un client mail encode un « é » — ceux de plus de huit lettres, et une
// douzaine écartés à la main parce qu'associés au hasard à deux autres ils
// donneraient une lecture désagréable sur la page publique de quelqu'un.
// Le coût en entropie est nul ; le coût de ne pas le faire se paierait une
// fois, publiquement.
//
// **La liste est gelée.** Retirer ou réordonner un mot ne casserait rien
// en soi — les noms sont stockés, pas recalculés — mais en ajouter réduit
// la part de hasard des anciens noms, et en retirer laisse des adresses
// qu'on ne saurait plus produire. On n'y touche pas sans raison écrite.
//
// 1670 mots, donc 4.66 milliard de combinaisons de trois mots (2^32). C'est
// l'ordre de grandeur de what3words. Moins qu'un identifiant aléatoire de
// seize caractères, et c'est assumé : la contrepartie est la limitation de
// débit sur les pages publiques (voir server/server.js), sans laquelle
// deviner une adresse ne coûterait rien à celui qui essaie.

export const MOTS_PUBLICATION = [
  'abaisser', 'abandon', 'abdiquer', 'abeille', 'abolir', 'aborder', 'aboutir', 'aboyer',
  'abrasif', 'abreuver', 'abriter', 'abroger', 'abrupt', 'absence', 'absolu', 'absurde',
  'abusif', 'abyssal', 'acajou', 'acarien', 'accabler', 'accepter', 'acclamer', 'accolade',
  'accroche', 'accuser', 'acerbe', 'achat', 'acheter', 'aciduler', 'acier', 'acompte',
  'acronyme', 'acteur', 'actif', 'actuel', 'adepte', 'adjectif', 'adjuger', 'admettre',
  'admirer', 'adopter', 'adorer', 'adoucir', 'adresse', 'adroit', 'adulte', 'adverbe',
  'affaire', 'affecter', 'affiche', 'affreux', 'affubler', 'agacer', 'agencer', 'agile',
  'agiter', 'agrafer', 'agrume', 'aider', 'aiguille', 'ailier', 'aimable', 'aisance',
  'ajouter', 'ajuster', 'alchimie', 'alerte', 'algue', 'aliment', 'alliage', 'allouer',
  'allumer', 'alourdir', 'alpaga', 'altesse', 'amateur', 'ambigu', 'ambre', 'amertume',
  'amidon', 'amiral', 'amorcer', 'amour', 'amovible', 'amphibie', 'ampleur', 'amusant',
  'analyse', 'anaphore', 'anarchie', 'anatomie', 'ancien', 'angle', 'angoisse', 'anguleux',
  'animal', 'annexer', 'annonce', 'annuel', 'anodin', 'anomalie', 'anonyme', 'anormal',
  'antenne', 'antidote', 'anxieux', 'apaiser', 'aplanir', 'apologie', 'appareil', 'appeler',
  'apporter', 'appuyer', 'aquarium', 'aqueduc', 'arbitre', 'arbuste', 'ardeur', 'ardoise',
  'argent', 'arlequin', 'armature', 'armoire', 'armure', 'arpenter', 'arracher', 'arriver',
  'arroser', 'arsenic', 'article', 'aspect', 'asphalte', 'aspirer', 'assaut', 'asservir',
  'assiette', 'associer', 'assurer', 'asticot', 'astre', 'astuce', 'atelier', 'atome',
  'atrium', 'atroce', 'attaque', 'attentif', 'attirer', 'attraper', 'aubaine', 'auberge',
  'audace', 'audible', 'augurer', 'aurore', 'automne', 'autruche', 'avaler', 'avancer',
  'avarice', 'avenir', 'averse', 'aveugle', 'aviateur', 'avide', 'avion', 'aviser',
  'avoine', 'avouer', 'avril', 'axial', 'axiome', 'badge', 'bagage', 'baguette',
  'baignade', 'balancer', 'balcon', 'baleine', 'balisage', 'bambin', 'bancaire', 'bandage',
  'banlieue', 'banquier', 'barbier', 'baril', 'baron', 'barque', 'barrage', 'bassin',
  'bastion', 'bataille', 'bateau', 'batterie', 'baudrier', 'bavarder', 'belette', 'belote',
  'berceau', 'berger', 'berline', 'bermuda', 'besace', 'besogne', 'beurre', 'biberon',
  'bicycle', 'bidule', 'bijou', 'bilan', 'bilingue', 'billard', 'binaire', 'biologie',
  'biopsie', 'biotype', 'biscuit', 'bison', 'bistouri', 'bitume', 'bizarre', 'blafard',
  'blague', 'blanchir', 'blessant', 'blinder', 'blond', 'bloquer', 'blouson', 'bobard',
  'bobine', 'boire', 'boiser', 'bolide', 'bonbon', 'bondir', 'bonheur', 'bonifier',
  'bonus', 'bordure', 'borne', 'botte', 'boucle', 'boueux', 'bougie', 'boulon',
  'bouquin', 'bourse', 'boussole', 'boutique', 'boxeur', 'branche', 'brasier', 'brave',
  'brebis', 'breuvage', 'bricoler', 'brigade', 'brillant', 'brioche', 'brique', 'brochure',
  'broder', 'bronzer', 'brousse', 'broyeur', 'brume', 'brusque', 'bruyant', 'buffle',
  'buisson', 'bulletin', 'bureau', 'burin', 'bustier', 'butiner', 'butoir', 'buvable',
  'buvette', 'cabanon', 'cabine', 'cachette', 'cadeau', 'cadre', 'caillou', 'caisson',
  'calculer', 'calepin', 'calibre', 'calmer', 'calomnie', 'calvaire', 'camarade', 'camion',
  'campagne', 'canal', 'caneton', 'canon', 'cantine', 'canular', 'capable', 'caporal',
  'caprice', 'capsule', 'capter', 'capuche', 'carabine', 'carbone', 'caresser', 'caribou',
  'carnage', 'carotte', 'carreau', 'carton', 'cascade', 'casier', 'casque', 'cassure',
  'causer', 'caution', 'cavalier', 'caverne', 'caviar', 'ceinture', 'cellule', 'cendrier',
  'censurer', 'central', 'cercle', 'cerise', 'cerner', 'cerveau', 'cesser', 'chagrin',
  'chaise', 'chaleur', 'chambre', 'chance', 'chapitre', 'charbon', 'chasseur', 'chaton',
  'chausson', 'chavirer', 'chemise', 'chenille', 'chercher', 'cheval', 'chien', 'chiffre',
  'chignon', 'chiot', 'chlorure', 'chocolat', 'choisir', 'chose', 'chouette', 'chrome',
  'chute', 'cigare', 'cigogne', 'cimenter', 'cintrer', 'circuler', 'cirer', 'cirque',
  'citerne', 'citoyen', 'citron', 'civil', 'clairon', 'clameur', 'claquer', 'classe',
  'clavier', 'client', 'cligner', 'climat', 'clivage', 'cloche', 'clonage', 'cloporte',
  'cobalt', 'cobra', 'cocasse', 'cocotier', 'coder', 'codifier', 'coffre', 'cogner',
  'coiffer', 'coincer', 'colibri', 'colline', 'colmater', 'colonel', 'combat', 'commande',
  'compact', 'concert', 'conduire', 'confier', 'congeler', 'connoter', 'consonne', 'contact',
  'convexe', 'copain', 'copie', 'corail', 'corbeau', 'cordage', 'corniche', 'corpus',
  'correct', 'cosmique', 'costume', 'coton', 'coude', 'coupure', 'courage', 'couteau',
  'couvrir', 'coyote', 'crabe', 'crainte', 'cravate', 'crayon', 'creuser', 'crevette',
  'cribler', 'crier', 'cristal', 'croire', 'croquer', 'crotale', 'crucial', 'crypter',
  'cubique', 'cueillir', 'cuisine', 'cuivre', 'culminer', 'cultiver', 'cumuler', 'cupide',
  'curatif', 'curseur', 'cyanure', 'cycle', 'cylindre', 'cynique', 'daigner', 'damier',
  'danger', 'danseur', 'dauphin', 'demander', 'demeurer', 'dentelle', 'descente', 'dessiner',
  'destrier', 'devancer', 'devenir', 'deviner', 'devoir', 'diable', 'dialogue', 'diamant',
  'dicter', 'digital', 'digne', 'diluer', 'dimanche', 'diminuer', 'dioxyde', 'directif',
  'diriger', 'discuter', 'disposer', 'dissiper', 'distance', 'divertir', 'diviser', 'docile',
  'docteur', 'dogme', 'doigt', 'domaine', 'domicile', 'dompter', 'donateur', 'donjon',
  'donner', 'dopamine', 'dortoir', 'dorure', 'dosage', 'doseur', 'dossier', 'dotation',
  'douanier', 'double', 'douceur', 'douter', 'doyen', 'dragon', 'draper', 'dresser',
  'dribbler', 'droiture', 'duperie', 'duplexe', 'durable', 'durcir', 'dynastie', 'effacer',
  'effectif', 'effigie', 'effort', 'effrayer', 'effusion', 'emballer', 'embellir', 'embryon',
  'emmener', 'empereur', 'employer', 'emporter', 'emprise', 'encadrer', 'enclave', 'encoche',
  'endiguer', 'endosser', 'endroit', 'enduire', 'enfance', 'enfermer', 'enfouir', 'engager',
  'engin', 'englober', 'enjamber', 'enjeu', 'enlever', 'ennemi', 'ennuyeux', 'enrichir',
  'enrobage', 'enseigne', 'entasser', 'entendre', 'entier', 'entourer', 'entraver', 'envahir',
  'enviable', 'envoyer', 'enzyme', 'erreur', 'escalier', 'espadon', 'espoir', 'esprit',
  'esquiver', 'essayer', 'essence', 'essieu', 'essorer', 'estime', 'estomac', 'estrade',
  'ethnie', 'euphorie', 'exact', 'exaucer', 'exceller', 'excitant', 'exclusif', 'excuse',
  'exemple', 'exercer', 'exhaler', 'exhorter', 'exigence', 'exiler', 'exister', 'exotique',
  'explorer', 'exposer', 'exprimer', 'exquis', 'extensif', 'extraire', 'exulter', 'fable',
  'fabuleux', 'facette', 'facile', 'facture', 'faiblir', 'falaise', 'fameux', 'famille',
  'farceur', 'farfelu', 'farine', 'farouche', 'fasciner', 'fatal', 'fatigue', 'faucon',
  'fautif', 'faveur', 'favori', 'femme', 'fendoir', 'fermer', 'ferveur', 'festival',
  'feuille', 'feutre', 'fiasco', 'ficeler', 'fictif', 'figure', 'filature', 'filetage',
  'filleul', 'filmer', 'filou', 'filtrer', 'financer', 'finir', 'fiole', 'firme',
  'fissure', 'fixer', 'flairer', 'flamme', 'flasque', 'flatteur', 'fleur', 'flexion',
  'flocon', 'flore', 'fluctuer', 'fluide', 'fluvial', 'fonderie', 'fongible', 'fontaine',
  'forcer', 'forgeron', 'formuler', 'fortune', 'fossile', 'foudre', 'fouiller', 'foulure',
  'fourmi', 'fragile', 'fraise', 'franchir', 'frapper', 'frayeur', 'freiner', 'frelon',
  'friable', 'friction', 'frisson', 'frivole', 'froid', 'fromage', 'frontal', 'frotter',
  'fruit', 'fugitif', 'fuite', 'fureur', 'furieux', 'furtif', 'fusion', 'futur',
  'gagner', 'galaxie', 'galerie', 'gambader', 'garantir', 'gardien', 'garnir', 'garrigue',
  'gazelle', 'gazon', 'gendarme', 'genou', 'gentil', 'germe', 'gestuel', 'geyser',
  'gibier', 'gicler', 'girafe', 'givre', 'glace', 'glaive', 'glisser', 'globe',
  'gloire', 'glorieux', 'golfeur', 'gomme', 'gonfler', 'gorge', 'gorille', 'goudron',
  'gouffre', 'goulot', 'goupille', 'gourmand', 'goutte', 'graduel', 'graffiti', 'graine',
  'grand', 'grappin', 'gratuit', 'gravir', 'grenat', 'griffure', 'griller', 'grimper',
  'grogner', 'gronder', 'grotte', 'groupe', 'gruger', 'grutier', 'guerrier', 'guide',
  'guimauve', 'guitare', 'gustatif', 'gymnaste', 'gyrostat', 'habitude', 'hachoir', 'halte',
  'hameau', 'hangar', 'hanneton', 'haricot', 'harmonie', 'harpon', 'hasard', 'herbe',
  'hermine', 'heureux', 'hiberner', 'hibou', 'hilarant', 'histoire', 'hiver', 'homard',
  'hommage', 'honneur', 'honorer', 'horde', 'horizon', 'horloge', 'hormone', 'horrible',
  'houleux', 'housse', 'hublot', 'huileux', 'humain', 'humble', 'humide', 'humour',
  'hurler', 'hydromel', 'hymne', 'hypnose', 'idylle', 'ignorer', 'iguane', 'illicite',
  'illusion', 'image', 'imbiber', 'imiter', 'immense', 'immobile', 'immuable', 'impact',
  'implorer', 'imposer', 'imprimer', 'imputer', 'incarner', 'incendie', 'incident', 'incliner',
  'incolore', 'indexer', 'indice', 'inductif', 'ineptie', 'inexact', 'infini', 'infliger',
  'informer', 'infusion', 'inhaler', 'inhiber', 'injecter', 'injure', 'innocent', 'inoculer',
  'inonder', 'inscrire', 'insecte', 'insigne', 'insolite', 'inspirer', 'instinct', 'insulter',
  'intact', 'intense', 'intime', 'intrigue', 'intuitif', 'inutile', 'invasion', 'inventer',
  'inviter', 'invoquer', 'ironique', 'irradier', 'irriter', 'isoler', 'ivoire', 'ivresse',
  'jaguar', 'jaillir', 'jambe', 'janvier', 'jardin', 'jauger', 'jaune', 'javelot',
  'jetable', 'jeton', 'jeudi', 'jeunesse', 'joindre', 'joncher', 'jongler', 'joueur',
  'jouissif', 'journal', 'jovial', 'joyau', 'joyeux', 'jubiler', 'jugement', 'junior',
  'jupon', 'juriste', 'justice', 'juteux', 'kayak', 'kimono', 'kiosque', 'label',
  'labial', 'labourer', 'lactose', 'lagune', 'laine', 'laisser', 'laitier', 'lambeau',
  'lamelle', 'lampe', 'lanceur', 'langage', 'lanterne', 'lapin', 'largeur', 'larme',
  'laurier', 'lavabo', 'lavoir', 'lecture', 'lessive', 'lettre', 'levier', 'lexique',
  'liasse', 'libre', 'licence', 'licorne', 'ligature', 'ligoter', 'ligue', 'limer',
  'limite', 'limonade', 'limpide', 'lingot', 'lionceau', 'liquide', 'lister', 'lithium',
  'litige', 'littoral', 'livreur', 'logique', 'lointain', 'loisir', 'lombric', 'loterie',
  'louer', 'lourd', 'loutre', 'louve', 'loyal', 'lubie', 'lucide', 'lucratif',
  'lueur', 'lugubre', 'luisant', 'lunaire', 'lundi', 'luron', 'lutter', 'luxueux',
  'machine', 'magasin', 'magenta', 'magique', 'maigre', 'maillon', 'maintien', 'mairie',
  'maison', 'majorer', 'malaxer', 'malheur', 'malice', 'mallette', 'mammouth', 'mandater',
  'maniable', 'manquant', 'manteau', 'manuel', 'marathon', 'marbre', 'marchand', 'mardi',
  'maritime', 'marqueur', 'marron', 'marteler', 'mascotte', 'massif', 'matraque', 'maudire',
  'maussade', 'mauve', 'maximal', 'meilleur', 'membre', 'mener', 'menhir', 'mensonge',
  'mentor', 'mercredi', 'merle', 'messager', 'mesure', 'meuble', 'miauler', 'microbe',
  'miette', 'mignon', 'migrer', 'milieu', 'million', 'mimique', 'mince', 'minimal',
  'minorer', 'minute', 'miracle', 'miroiter', 'missile', 'mixte', 'mobile', 'moderne',
  'moelleux', 'mondial', 'moniteur', 'monnaie', 'monotone', 'monstre', 'montagne', 'monument',
  'moqueur', 'morceau', 'morsure', 'moteur', 'motif', 'mouche', 'moufle', 'moulin',
  'mousson', 'mouton', 'mouvant', 'multiple', 'munition', 'muraille', 'murmure', 'muscle',
  'musicien', 'mutation', 'muter', 'mutuel', 'myriade', 'myrtille', 'mythique', 'nageur',
  'nappe', 'narquois', 'narrer', 'natation', 'nation', 'nature', 'naufrage', 'nautique',
  'navire', 'nectar', 'neige', 'nerveux', 'nettoyer', 'neurone', 'neutron', 'neveu',
  'niche', 'nickel', 'nitrate', 'niveau', 'noble', 'nocif', 'nocturne', 'noirceur',
  'noisette', 'nomade', 'nombreux', 'nommer', 'normatif', 'notable', 'notifier', 'notoire',
  'nourrir', 'nouveau', 'novateur', 'novembre', 'novice', 'nuage', 'nuancer', 'nuire',
  'nuisible', 'nuptial', 'nuque', 'nutritif', 'objectif', 'obliger', 'obscur', 'observer',
  'obstacle', 'obtenir', 'obturer', 'occasion', 'occuper', 'octobre', 'octroyer', 'octupler',
  'oculaire', 'odeur', 'odorant', 'offenser', 'officier', 'offrir', 'ogive', 'oiseau',
  'oisillon', 'olfactif', 'olivier', 'ombrage', 'omettre', 'onctueux', 'onduler', 'onirique',
  'opale', 'opaque', 'opinion', 'opportun', 'opprimer', 'opter', 'optique', 'orageux',
  'orange', 'orbite', 'ordonner', 'oreille', 'organe', 'orgueil', 'orifice', 'ornement',
  'orque', 'ortie', 'osciller', 'osmose', 'ossature', 'otarie', 'ouragan', 'ourson',
  'outil', 'outrager', 'ouvrage', 'ovation', 'oxyde', 'ozone', 'paisible', 'palace',
  'palourde', 'palper', 'panache', 'panda', 'pangolin', 'paniquer', 'panneau', 'panorama',
  'pantalon', 'papaye', 'papier', 'papoter', 'papyrus', 'paradoxe', 'parcelle', 'paresse',
  'parfumer', 'parler', 'parole', 'parrain', 'parsemer', 'partager', 'parure', 'parvenir',
  'passion', 'paternel', 'patience', 'patron', 'pavillon', 'pavoiser', 'payer', 'paysage',
  'peigne', 'peintre', 'pelage', 'pelle', 'pelouse', 'peluche', 'pendule', 'pensif',
  'perdrix', 'perforer', 'permuter', 'perplexe', 'persil', 'perte', 'peser', 'petit',
  'peuple', 'pharaon', 'phobie', 'phoque', 'photon', 'phrase', 'physique', 'piano',
  'pictural', 'pierre', 'pieuvre', 'pilote', 'pinceau', 'pipette', 'piquer', 'pirogue',
  'piscine', 'piston', 'pivoter', 'pixel', 'pizza', 'placard', 'plafond', 'plaisir',
  'planer', 'plaque', 'plastron', 'plateau', 'pleurer', 'plexus', 'pliage', 'plomb',
  'plonger', 'pluie', 'plumage', 'pochette', 'pointe', 'poirier', 'poisson', 'poivre',
  'polaire', 'policier', 'pollen', 'polygone', 'pommade', 'pompier', 'ponctuel', 'poney',
  'portique', 'position', 'posture', 'potager', 'poteau', 'potion', 'pouce', 'poulain',
  'poumon', 'pourpre', 'poussin', 'pouvoir', 'prairie', 'pratique', 'primitif', 'prince',
  'prison', 'priver', 'prodige', 'profond', 'proie', 'projeter', 'prologue', 'promener',
  'propre', 'prouesse', 'proverbe', 'prudence', 'pruneau', 'psychose', 'public', 'puceron',
  'puiser', 'pulpe', 'pulsar', 'punaise', 'punitif', 'pupitre', 'purifier', 'puzzle',
  'pyramide', 'quasar', 'querelle', 'question', 'quitter', 'quotient', 'racine', 'raconter',
  'radieux', 'ragondin', 'raideur', 'raisin', 'ralentir', 'rallonge', 'ramasser', 'rapide',
  'rasage', 'ratisser', 'ravager', 'ravin', 'rayonner', 'recevoir', 'recruter', 'reculer',
  'recycler', 'redouter', 'refaire', 'refrain', 'refuge', 'rejeter', 'rejouer', 'relatif',
  'relever', 'relief', 'remarque', 'remise', 'remonter', 'remplir', 'remuer', 'renard',
  'renfort', 'renifler', 'renoncer', 'rentrer', 'renvoi', 'replier', 'reporter', 'reprise',
  'reptile', 'requin', 'respect', 'rester', 'retenir', 'retomber', 'retracer', 'revanche',
  'revivre', 'richesse', 'rideau', 'rieur', 'rigide', 'rigoler', 'rincer', 'riposter',
  'risible', 'risque', 'rituel', 'rival', 'rocheux', 'romance', 'rompre', 'ronce',
  'rondin', 'roseau', 'rosier', 'rotatif', 'rotor', 'rotule', 'rouge', 'rouille',
  'rouleau', 'routine', 'royaume', 'ruban', 'rubis', 'ruche', 'ruelle', 'rugueux',
  'ruiner', 'ruisseau', 'ruser', 'rustique', 'rythme', 'sabler', 'saboter', 'sabre',
  'sacoche', 'safari', 'sagesse', 'saisir', 'salade', 'salive', 'salon', 'saluer',
  'samedi', 'sanction', 'sarcasme', 'sardine', 'saturer', 'saugrenu', 'saumon', 'sauter',
  'sauvage', 'savant', 'savonner', 'scalpel', 'scandale', 'sceptre', 'science', 'scinder',
  'score', 'scrutin', 'sculpter', 'secouer', 'seigneur', 'semaine', 'sembler', 'semence',
  'sensible', 'sentence', 'serein', 'sergent', 'serrure', 'service', 'sevrage', 'sextuple',
  'siffler', 'sigle', 'signal', 'silence', 'silicium', 'simple', 'sinistre', 'siphon',
  'sirop', 'sismique', 'situer', 'skier', 'social', 'socle', 'sodium', 'soigneux',
  'soldat', 'soleil', 'solitude', 'soluble', 'sombre', 'sommeil', 'somnoler', 'sonde',
  'songeur', 'sonnette', 'sonore', 'sorcier', 'sortir', 'sosie', 'sottise', 'soucieux',
  'soudure', 'souffle', 'soulever', 'soupape', 'source', 'soutirer', 'souvenir', 'spacieux',
  'spatial', 'spiral', 'stable', 'station', 'sternum', 'stimulus', 'stipuler', 'strict',
  'studieux', 'styliste', 'sublime', 'substrat', 'subtil', 'subvenir', 'sucre', 'suffixe',
  'suiveur', 'sulfate', 'superbe', 'supplier', 'surface', 'suricate', 'surmener', 'surprise',
  'sursaut', 'survie', 'suspect', 'syllabe', 'symbole', 'synapse', 'syntaxe', 'tabac',
  'tablier', 'tactile', 'tailler', 'talent', 'talisman', 'talonner', 'tambour', 'tamiser',
  'tangible', 'tapis', 'taquiner', 'tarder', 'tarif', 'tartine', 'tasse', 'tatami',
  'tatouage', 'taupe', 'taureau', 'taxer', 'temporel', 'tenaille', 'tendre', 'teneur',
  'tenir', 'tension', 'terminer', 'terne', 'terrible', 'texte', 'thorax', 'tibia',
  'timide', 'tirelire', 'tiroir', 'tissu', 'titane', 'titre', 'tituber', 'toboggan',
  'tomate', 'tonique', 'tonneau', 'toponyme', 'torche', 'tordre', 'tornade', 'torpille',
  'torrent', 'torse', 'tortue', 'totem', 'toucher', 'tournage', 'tousser', 'toxine',
  'traction', 'trafic', 'tragique', 'trahir', 'train', 'trancher', 'travail', 'tremper',
  'treuil', 'triage', 'tribunal', 'tricoter', 'trilogie', 'triomphe', 'tripler', 'triturer',
  'trivial', 'trombone', 'tronc', 'tropical', 'troupeau', 'tuile', 'tulipe', 'tumulte',
  'tunnel', 'turbine', 'tuteur', 'tutoyer', 'tuyau', 'tympan', 'typhon', 'typique',
  'tyran', 'ubuesque', 'ultime', 'ultrason', 'unanime', 'unifier', 'union', 'unique',
  'unitaire', 'univers', 'uranium', 'urbain', 'urticant', 'usage', 'usine', 'usuel',
  'usure', 'utile', 'utopie', 'vacarme', 'vaccin', 'vagabond', 'vague', 'vaillant',
  'vaincre', 'vaisseau', 'valable', 'valise', 'vallon', 'valve', 'vampire', 'vanille',
  'vapeur', 'varier', 'vaseux', 'vassal', 'vaste', 'vecteur', 'vedette', 'veinard',
  'vendredi', 'venger', 'venimeux', 'ventouse', 'verdure', 'vernir', 'verrou', 'verser',
  'vertu', 'veston', 'vexant', 'vexer', 'viaduc', 'viande', 'victoire', 'vidange',
  'vignette', 'vigueur', 'vilain', 'village', 'vinaigre', 'violon', 'virement', 'virtuose',
  'virus', 'visage', 'viseur', 'vision', 'visqueux', 'visuel', 'vital', 'vitesse',
  'viticole', 'vitrine', 'vivace', 'vivipare', 'vocation', 'voguer', 'voile', 'voisin',
  'voiture', 'volaille', 'volcan', 'voltiger', 'volume', 'vortex', 'voter', 'vouloir',
  'voyage', 'voyelle', 'wagon', 'yacht', 'zeste', 'zoologie',
]
